# Generated by Django 2.0.7 on 2018-09-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('frequency', models.DecimalField(decimal_places=2, max_digits=3)),
                ('image', models.ImageField(upload_to='components/processors')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_le_id', to='main.ListElements')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_le_id', to='main.ListElements')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socket_le_id', to='main.ListElements')),
            ],
        ),
        migrations.AddField(
            model_name='listelements',
            name='syslist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lists'),
        ),
    ]
