# Generated by Django 2.0.7 on 2018-08-01 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
                ('serial_number', models.CharField(max_length=128)),
                ('date_created', models.DateField(blank=True, default=datetime.date.today)),
                ('keywords', models.CharField(max_length=256)),
            ],
        ),
    ]
