# Generated by Django 2.0.7 on 2018-09-02 17:06

from django.db import migrations

def seed_superuser(apps,schema_editor):
    pass

def seed_system_lists(apps,schema_editor):
    Lists = apps.get_model('main','Lists')
    Lists(code='PROC_MODEL', value="Processor model").save()
    Lists(code='PROC_SOCKET', value="Processor socket").save()
    Lists(code='PROC_BRAND', value="Processor brand").save()

def seed_processor_list_elements(apps,schema_editor):
    Lists = apps.get_model('main','Lists')
    ListElements = apps.get_model('main','ListElements')
    procModelList = Lists.objects.filter(code="PROC_MODEL").get()
    procSocketList = Lists.objects.filter(code="PROC_SOCKET").get()
    procBrandList = Lists.objects.filter(code="PROC_BRAND").get()

    ListElements(value="i3 560",syslist_id=procModelList).save()
    ListElements(value="i3 570",syslist_id=procModelList).save()
    ListElements(value="i3 580",syslist_id=procModelList).save()

    ListElements(value="LGA 1155",syslist_id=procSocketList).save()
    ListElements(value="LGA 1156",syslist_id=procSocketList).save()

    ListElements(value="Intel",syslist_id=procBrandList).save()
    ListElements(value="AMD",syslist_id=procBrandList).save()
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_superuser),
        migrations.RunPython(seed_system_lists),
        migrations.RunPython(seed_processor_list_elements),
    ]