# Generated by Django 2.0.7 on 2018-08-02 14:44

from django.db import migrations


def seed_computers(apps,schema_editor):
    Computer = apps.get_model('main','Computer')
    Computer(title = "Lenovo IdeaCentre 310", description = "Operacijski sistem: N/A, Procesor: AMD A6-9230, RAM: 4GB",
            serial_number="631-230-12BAX321419", date_created = "2018-3-11", keywords="AMD Proc, Lenovo, IdeaCentre").save()
    Computer(title = "mimovrste Nitro PF7", description = "Operacijski sistem: WIN10, Procesor: i5 7400, RAM: 8GB",
            serial_number="312-555-63ASX31A9", date_created = "2018-3-11", keywords="Intel, mimovrste, PF7").save()
    Computer(title = "HP Ai0 Pavilion", description = "Operacijski sistem: Ubuntu, Procesor: i7-7700T, RAM: 16GB",
            serial_number="333-111-765AXC321678", date_created = "2018-3-11", keywords="Intel, Linux, Pavilion").save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_computers),
    ]
